version: '3.8'
services:

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - mongo-express
    volumes:
      - ./app:/app

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 3
      timeout: 10s

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8080:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
